### ISSUE TITLE
is it possible to use an authenticated url like rtsp://admin:admin@link ?

### ISSUE THREAD

**Issue by guazarito** [disono/cordova-rtsp#1]
Hi guys, please help me.

I could play a video using this example url: rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov. It works fine.
But, when I try to use my needed url, which uses authentication, like rtsp://admin:admin@myurl:554/live, It can't be played. 
I guess that the error is regarding the authentication. Does someone know how to workaround it?

Thanks,

Gustavo

**Comment by disono** [comment]
you can libVLC plugin https://github.com/disono/cordova-plugin-libVLC
